services:
  mern-fe:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  mern-be:
    build:
      context: ./server
      args: 
       - ATLAS_URI=${ATLAS_URI:-default}
       - SESSION_SECRET=${SESSION_SECRET:-default}
      dockerfile: Dockerfile
    environment:
       - ATLAS_URI=${ATLAS_URI:-default}
       - SESSION_SECRET=${SESSION_SECRET:-default}
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    volumes:
      - mern-db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"
volumes:
  mern-db: