apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: yash357/social-media-app-mern-fe
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://node-service:3000/api
